extra_css:
  - css/extras.css
nav:
  - 'index.md'
  - 'Setup':
      - 'setup/deployment.md'
      - 'setup/configuration.md'
  - 'User Guide':
    - 'user-guide/navigating.md'
    - 'user-guide/adding-entries.md'
    - 'user-guide/using-timers.md'
  - 'import-export.md'
  - 'api.md'
  - 'contributing.md'
theme:
  name: material
  favicon: assets/images/favicon.svg
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - search.share
    - search.suggest
  logo: assets/images/logo.svg
  palette:
    scheme: slate
repo_name: babybuddy/babybuddy
repo_url: https://github.com/babybuddy/babybuddy
site_name: Baby Buddy Documentation
site_url: https://docs.baby-buddy.net