databases:
  - name: babybuddy
    plan: free

services:
  - type: web
    name: babybuddy
    plan: free
    env: python
    buildCommand: "python -m pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "bash Procfile.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: babybuddy
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: babybuddy.settings.render
      - key: PYTHON_VERSION
        value: 3.10.4
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
