databases:
  - name: db
    plan: free

services:
  - type: web
    name: app
    env: python
    buildCommand: "./.render.com/build.sh"
    startCommand: "gunicorn babybuddy.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: babybuddy.settings.render
      - key: PYTHON_VERSION
        value: 3.10.4
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
